<?php
namespace Emeric0101\PHPAngular\Service\Install;
use Emeric0101\PHPAngular\Service\Utils;
class Routing {

    private function getComponents() {
        $path = 'app/Component';
        $array = [];
        $files = scandir($path);
        $entities = [];
        foreach ($files as $file) {
            if ($file == '.' || $file == '..') {continue;}
            if (is_dir($path .'/'. $file)) {
                $ssFiles = scandir($path .'/'. $file);
                foreach ($ssFiles as $ssFile) {
					if (!is_dir( $path .'/'. $file .'/'. $ssFile)) {continue;}
					if ($ssFile == "." || $ssFile == '..') {continue;}
					$name = ucFirst($file);
					// If module name different than component name
					if ($file != $ssFile) {
						$name .=  ucFirst($ssFile);
					}
                    $array[] =
                    [
                        'path' => $file .'/'. $ssFile . '/' . $ssFile,
                        'name' => $name
                    ];
                }
            }
        }
        return $array;
    }

    public function createRoute()
    {
		$declaration = [];
        $components = $this->getComponents();
		$code = '/** This file is autogenerated */' . PHP_EOL;
		$code .= '
import { ModuleWithProviders }  from "@angular/core";
import { Routes, RouterModule } from "@angular/router";' . PHP_EOL;
		foreach ($components as $comp)
		{
			$declaration[] = $comp['name'];
			$code .= 'import { ' . $comp['name'] . ' } from "./Component/' . $comp['path'] . '";'.PHP_EOL;
		}
		$code .= 'const appRoutes: Routes = [' . PHP_EOL;
		foreach ($components as $comp)
		{
			$code .= '	{
		path: "' . $comp['name'] . '",
		component : '. $comp['name'] . '
	},' . PHP_EOL;
		}
		$code .= '	{
		path: "",
		redirectTo: "/Index",
		pathMatch: "full"
	}
];
export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);
export const declarations = [' . implode(',', $declaration) . '];' . PHP_EOL;

		Utils::file_force_contents("app/app.routing.ts", $code);
    }
}
